title: Intermediate HTML/CSS
hero_image: images/banner.png
description: Take your website design skills further!
theme: navy # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
version: 1
listed: true
ingredient: false
copyedit: true
last_tested: "2018-04-06"
interests: "music, literature, cybersecurity-and-cryptography, weather, photography, games, animals, big-project, space, art"
technologies: "html-css-javascript"
software: "html-css-javascript"
site_areas: coderdojo
steps:
- title: Introduction
- title: What you will need
- title: Getting set up
- title: All the colours!
- title: Organising your page
- title: Design some themes
- title: Individual style
- title: See the code on other websites!
- title: Automatically adjust the size
- title: Animation
- title: Add hover effects
