---
title: Bird watch website 2.0
hero_image: images/banner.png
description: Take your website design skills further!
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3.0.0
last_tested: '2018-04-06'
steps:
- title: Introduction
  completion: engaged
- title: Getting set up
- title: All the colours!
- title: Organising your page
- title: Design some themes
- title: Individual style
- title: See the code on other websites!
- title: Automatically adjust the size
- title: Animation
  completion: internal
- title: Add hover effects
