---
title: बर्ड वॉच वेबसाइट 2.0
hero_image: images/banner.png
description: अपने वेबसाइट डिजाइन कौशल को और आगे ले जाएं!
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: html-css-javascript
site_areas: coderdojo, projects
hardware: ''
software: html-css-javascript
version: 3.0.0
last_tested: '2018-04-06'
steps:
- title: भूमिका
- title: शुरू करने के लिए
- title: सभी रंग!
- title: अपने पृष्ठ का आयोजन
  completion:
  - engaged
- title: कुछ थीम डिजाइन करें
- title: व्यक्तिगत स्टाइल (style)
- title: अन्य वेबसाइटों पर कोड देखें!
- title: स्वचालित रूप से आकार नियमित करें
- title: एनीमेशन
- title: होवर प्रभाव जोड़ें
  completion:
  - internal
